theme:
  name: default
  default_appearance: dark
  default_palette: snow-lynx
  features:
  - navigation.breadcrumbs
  - navigation.toc
  - navigation.toc.sticky
  - navigation.prev_next
  - navigation.back_to_top
  - content.code.copy
  - content.lightbox
  - content.reading_time
  - content.author
  - content.excerpts
  - content.children
  - search.suggest
  - search.highlight
  - footer.social
  - accessibility.skip_link
  max_tags_display: 10
  popular_tags_count: 20
