theme:
  name: default
  default_appearance: dark
  default_palette: snow-lynx
  show_reading_time: true
  show_author: true
  show_prev_next: true
  show_children_default: true
  show_excerpts_default: true
  max_tags_display: 10
  popular_tags_count: 20
